"""Alembic environment for the OPERATIONAL RUNTIME OVERLAY — a second, independent lineage.

The main lineage (``migrations/``) is one linear chain from ``0001_l2b_initial`` to
``0026_l2f2_phase_d_closure``, and every revision from ``0006`` on is an L2-F/L2-F2 *scientific*
campaign migration. The operational store deliberately stops at ``0005_l2e_feature_view``: it is
not a campaign database and must never grow twenty-one campaign tables just to receive a runtime
schema change. Appending the change at ``0027`` would force exactly that, and branching the main
graph would leave ``alembic upgrade head`` ambiguous for every deployment and every test.

So the runtime schema has its own lineage, tracked in its own version table
(``runtime.alembic_version_runtime``). The two chains never reference each other's revisions; the
overlay instead *requires* the main chain to be at exactly ``0005_l2e_feature_view`` and refuses
otherwise, which is also what structurally keeps it off the TRAIN (``0020``) and VALIDATION
(``0026``) stores. Nothing in ``migrations/`` is edited, re-parented, merged or stamped.

Like the main environment, the URL comes only from ``MINOS_DATABASE_URL`` and importing this
module opens no connection.
"""

from __future__ import annotations

from alembic import context

from minos_engine.storage.database import create_db_engine, database_url
from minos_engine.storage.runtime_decision_contract import (
    RUNTIME_OVERLAY_VERSION_TABLE,
    RUNTIME_OVERLAY_VERSION_TABLE_SCHEMA,
)

# Frozen, explicit snapshots — never autogenerated from ORM metadata (revision immutability),
# and deliberately NOT bound to ``Base.metadata``: the accepted DB-READY storage fingerprint
# hashes that metadata, so adding the overlay there would silently move an accepted gate.
target_metadata = None

_VERSION_TABLE_KWARGS = {
    "version_table": RUNTIME_OVERLAY_VERSION_TABLE,
    "version_table_schema": RUNTIME_OVERLAY_VERSION_TABLE_SCHEMA,
}


def run_migrations_offline() -> None:
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
        **_VERSION_TABLE_KWARGS,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_db_engine()
    try:
        with engine.connect() as connection:
            context.configure(
                connection=connection,
                target_metadata=target_metadata,
                include_schemas=True,
                transaction_per_migration=True,
                **_VERSION_TABLE_KWARGS,
            )
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
